#+TITLE: YAGNI
#+DATE: 2025-11-06

#+SUBTITLE: You are(n't)? gonna need it...
#+DESCRIPTION:
#+KEYWORDS: privacy security

#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP:  5.html

* Encrypt data using OpenPGP

** About

This post attempts to summarize the most frequent tasks when it comes to
encrypting data and managing encryption keys.

It focuses on the GNU Privacy Guard (GPG), which is the GNU's implementation of
OpenPGP. All the examples are executed from the command line using the =gpg=
command, but the concepts can be extended to other clients i.e Emacs,
OpenKeyChain, etc.

** Managing keys locally

Before starting to encrypt files, it's required to have some basic knowledge
about managing personal key pairs. This section doesn't consider the usage of a
key server.

*** Personal keys

To generate a new key pair (public/private) use the =--gen-key= switch. This
command will suggest sensible defaults and it will create a "revocation
certificate" which is stored in the =.gnupg/openpgp-revocs.d= folder.

#+begin_src sh
  gpg --gen-key
#+end_src

The generated key using this command /expires in 3 years/, to change the
expiration time or to make a key that doesn't expire, use the =--full-gen-key=
instead.

For other ways of generating key pairs, [[*See also][see]] the =gpg= man page.

*** View the keys in the keyring

To view the public keys available in the keyring use the =--list-keys= or =-k=.

#+begin_src sh
  gpg -k
#+end_src

An example of the output of the previous command:

#+begin_src text
  [keyboxd]
---------
pub   ed25519 2025-11-05 [SC] [expires: 2028-11-04]
      89AE120CA468BFC9D1B7EA6ECBD8D4A7A5681EDF
uid           [ultimate] test <test@test.com>
sub   cv25519 2025-11-05 [E] [expires: 2028-11-04]

pub   ed25519 2025-11-05 [SC]
      BAC76CAB4DD7F0B431104806C5C32C92869510D6
uid           [ultimate] test (comment) <test@test.com>
sub   cv25519 2025-11-05 [E]
#+end_src

Either the hex ID below the "pub" line, the name or the email address can be
used to identify a key.

*** Other people's public keys

To add a public key from a /trusted/ source to your "keyring", use the =--import=
command:

#+begin_src sh
  gpg --import persons_trusted_public_key_file
#+end_src

If you /know for sure/ that a public key belongs to the person who claims it,
then you can sign it and tell =gpg= that you trust the key:

#+begin_src sh
  gpg --sign-key key_identifier
#+end_src

/Note:/ Refer to the [[*View the keys in the keyring][previous section]] to see how to extract the key's identifier
using =gpg -k=.

** Encrypt

Now that we have basic knowledge about how manage the keyring, we can proceed to
explore the encryption step. For encrypting data there are a few relevant
command options to know about:

  - *encrypt (-e)*: Tells =gpg= that we intend to encrypt data. It takes an
    optional filename as an argument, this refers to the file to be encrypted;
    if no filename is provided then it reads the data from the standard input.
  - *recipient (-r)*: It takes an argument, which is the key identifier of the
    recipient to whom the data is to be encrypted. It's possible to provide
    multiple =--recipient= arguments if the message is intended for more than
    one person.
  - *armor (-a)*: This is an optional argument and it requests that the
    encrypted output is to be represented as readable ASCII rather than using
    the OpenPGP binary format.
  - *sign (-s)*: This optional argument requests that the encrypted output is to
    be signed with our "default-key". This way, the recipient can verify that
    the encrypted message comes from the person who claims to be the sender.

*** Messages

Once that we know about the command line options that can be used for encrypting
data, we can proceed to encrypt message.

To encrypt a message, we just need to know that if the =--encrypt= switch didn't
take a filename as an argument, then it reads its input from STDIN and that the
encrypted data will be sent to STDOUT. This means that in order to encrypt a
message it should be enough to redirect the standard input and output as in:
#+begin_src sh
  gpg --recipient Ritchie --recipient Buddy --armor --encrypt <<END > encrypted.txt.asc
  Let's rock!!
  <<END
#+end_src

*** Files

Given the previous section, we now know that we can pass a file name to the
=--encrypt= command and it'll encrypt it and generate a new file with the
encrypted data. The following example uses the option's "short names", and
includes multiple recipients (including the sender):

#+begin_src sh
  gpg -r Ritchie -r Buddy -r Me -sae rocknroll.txt
#+end_src

It'll generate an encrypted file with extension =gpg= if no =--armor= option was
used, otherwise the extension will be =asc=.

** Decrypt

Use the =--decrypt (-d)= switch to decrypt a message. This switch takes an
optional argument which is the name of the file to decrypt; if no filename is
provided, then it reads the date from STDIN. By default, the decrypted data will
be written in STDOUT unless the =--output (-o)= option is used, i.e:

#+begin_src sh
  gpg -o rocknroll.txt -d rocknroll.txt.asc
#+end_src

** Also important

1. If you encrypt a file and you don't include yourself as a "recipient" then
   you won't be able to decrypt it.
2. It's possible to "sign" data without encrypting it using the =--sign (-s)=
   switch, see the man page for more information.
3. The signature can be detached from the data using the =--detach-sign (-b)=
   switch.
4. Use the =--verify= option to verify the signature.
5. People use =openpgp= key servers to share their public keys. If one is to be
   used, make sure you use one that is reliable and follow the practices for
   verifying and trusting of the public keys.
6. If a key is compromised and/or needs to be removed, then it's important to
   "revoke" it. In a [[*Personal keys][previous section]], it was mentioned that a revocation
   certificate is created when a new key pair is created, this certificate can
   be used to revoke the key, refer to the [[*See also][next section]].

** See also
1. The [[https://www.gnupg.org/documentation/manuals/gnupg24/gpg.1.html][gpg man page]]
2. The [[https://en.wikipedia.org/wiki/Key_server_(cryptographic)][Key server]] article in Wikipedia
3. The [[https://www.digitalocean.com/community/tutorials/how-to-use-gpg-to-encrypt-and-sign-messages][GPG Tutorial]] by DigitalOcean
4. [[https://superuser.com/questions/1526283/how-to-revoke-a-gpg-key-and-upload-in-gpg-server][How to]] revoke a key
